# Business Rules Configuration for Australian Health Geography Data
# Domain-specific validation rules for Australian health and geographic datasets

version: "1.0"
schema_version: "2024-01"

# Australian Bureau of Statistics (ABS) specific business rules
abs_rules:
  statistical_areas:
    sa2_rules:
      - rule_id: "sa2_code_format"
        description: "SA2 codes must follow ABS 2021 ASGS format"
        validation_type: "pattern"
        pattern: "^[1-8][0-9]{8}$"
        severity: "error"
        
      - rule_id: "sa2_population_range"
        description: "SA2 areas typically have 3,000-25,000 residents"
        validation_type: "range"
        column: "usual_resident_population"
        min_value: 100        # Allow some flexibility for remote areas
        max_value: 50000      # Allow for high-density areas
        severity: "warning"
        
      - rule_id: "sa2_area_range"
        description: "SA2 geographic area should be reasonable"
        validation_type: "range"
        column: "geographic_area_sqkm"
        min_value: 0.1        # Minimum 0.1 sq km
        max_value: 50000      # Maximum 50,000 sq km (remote areas)
        severity: "warning"
    
    state_territory_mapping:
      - rule_id: "sa2_state_prefix"
        description: "SA2 code first digit must match state/territory"
        validation_type: "custom"
        mapping:
          "1": "NSW"    # New South Wales
          "2": "VIC"    # Victoria  
          "3": "QLD"    # Queensland
          "4": "SA"     # South Australia
          "5": "WA"     # Western Australia
          "6": "TAS"    # Tasmania
          "7": "NT"     # Northern Territory
          "8": "ACT"    # Australian Capital Territory
        severity: "error"

# Australian Institute of Health and Welfare (AIHW) business rules
aihw_rules:
  health_data_constraints:
    mortality_rates:
      - rule_id: "mortality_rate_range"
        description: "Age-standardised mortality rates should be realistic"
        validation_type: "range"
        column: "asr_mortality_rate"
        min_value: 0.0
        max_value: 50.0       # Per 1,000 population
        severity: "warning"
        
      - rule_id: "mortality_confidence_intervals"
        description: "Mortality rate confidence intervals must be valid"
        validation_type: "relationship"
        lower_bound_column: "asr_mortality_lower_ci"
        upper_bound_column: "asr_mortality_upper_ci"
        point_estimate_column: "asr_mortality_rate"
        severity: "error"
    
    hospitalisation_data:
      - rule_id: "hospital_separation_rates"
        description: "Hospital separation rates should be reasonable"
        validation_type: "range"
        column: "hospital_separations_per_1000"
        min_value: 0.0
        max_value: 2000.0     # Per 1,000 population
        severity: "warning"
        
      - rule_id: "principal_diagnosis_codes"
        description: "Principal diagnosis codes must be valid ICD-10-AM"
        validation_type: "reference"
        reference_dataset: "icd_10_am_codes"
        severity: "error"

# Medicare and Pharmaceutical Benefits Scheme (PBS) rules
medicare_pbs_rules:
  medicare_utilisation:
    - rule_id: "medicare_services_per_capita"
      description: "Medicare services per capita should be realistic"
      validation_type: "range"
      column: "medicare_services_per_capita"
      min_value: 0.0
      max_value: 100.0      # Annual services per person
      severity: "warning"
      
    - rule_id: "medicare_benefits_paid"
      description: "Medicare benefits paid should be reasonable"
      validation_type: "range"
      column: "medicare_benefits_paid_per_capita"
      min_value: 0.0
      max_value: 10000.0    # Annual AUD per capita
      severity: "warning"
  
  pbs_utilisation:
    - rule_id: "pbs_prescriptions_per_capita"
      description: "PBS prescriptions per capita should be realistic"
      validation_type: "range"
      column: "pbs_prescriptions_per_capita"
      min_value: 0.0
      max_value: 50.0       # Annual prescriptions per person
      severity: "warning"
      
    - rule_id: "pbs_cost_per_capita"
      description: "PBS cost per capita should be reasonable"
      validation_type: "range"
      column: "pbs_cost_per_capita"
      min_value: 0.0
      max_value: 5000.0     # Annual AUD per capita
      severity: "warning"

# Socio-Economic Indexes for Areas (SEIFA) business rules
seifa_rules:
  index_validation:
    - rule_id: "seifa_score_range"
      description: "SEIFA scores should be within expected range"
      validation_type: "range"
      columns: 
        - "seifa_irsad_score"
        - "seifa_irsed_score"  
        - "seifa_ier_score"
        - "seifa_ieo_score"
      min_value: 400        # Approximate minimum SEIFA score
      max_value: 1200       # Approximate maximum SEIFA score
      severity: "error"
      
    - rule_id: "seifa_decile_range"
      description: "SEIFA deciles must be 1-10"
      validation_type: "range"
      columns:
        - "seifa_irsad_decile"
        - "seifa_irsed_decile"
        - "seifa_ier_decile"
        - "seifa_ieo_decile"
      min_value: 1
      max_value: 10
      severity: "error"

# Census data business rules
census_rules:
  demographic_data:
    - rule_id: "age_group_totals"
      description: "Age group populations should sum to total population"
      validation_type: "summation_check"
      total_column: "total_population"
      component_columns:
        - "age_0_4_years"
        - "age_5_14_years"
        - "age_15_24_years"
        - "age_25_34_years"
        - "age_35_44_years"
        - "age_45_54_years"
        - "age_55_64_years"
        - "age_65_74_years"
        - "age_75_84_years"
        - "age_85_years_over"
      tolerance: 0.02       # 2% tolerance for rounding
      severity: "warning"
      
    - rule_id: "sex_distribution"
      description: "Male and female populations should sum to total"
      validation_type: "summation_check"
      total_column: "total_population"
      component_columns: ["male_population", "female_population"]
      tolerance: 0.01       # 1% tolerance
      severity: "warning"
      
  income_data:
    - rule_id: "income_quartiles"
      description: "Income quartiles should be ordered correctly"
      validation_type: "ordering_check"
      columns: 
        - "income_first_quartile"
        - "median_household_income_weekly"
        - "income_third_quartile"
      ascending: true
      severity: "error"

# Geographic consistency rules
geographic_consistency:
  spatial_relationships:
    - rule_id: "sa2_within_sa3"
      description: "SA2 areas must be within their parent SA3"
      validation_type: "hierarchy_check"
      child_column: "sa2_code"
      parent_column: "sa3_code"
      severity: "error"
      
    - rule_id: "coordinate_sa2_match"
      description: "Coordinates should be within SA2 boundary"
      validation_type: "spatial_containment"
      point_columns: ["longitude", "latitude"]
      boundary_column: "sa2_code"
      tolerance_metres: 1000    # 1km tolerance for centroids
      severity: "warning"

# Temporal consistency rules
temporal_consistency:
  time_series_validation:
    - rule_id: "population_growth_reasonable"
      description: "Population growth should be within reasonable bounds"
      validation_type: "time_series_change"
      column: "total_population"
      max_annual_change_percent: 15.0
      min_annual_change_percent: -10.0
      severity: "warning"
      
    - rule_id: "data_year_consistency"
      description: "All data in a batch should be from the same year"
      validation_type: "consistency_check"
      column: "data_year"
      severity: "error"

# Cross-dataset validation rules
cross_dataset_validation:
  population_consistency:
    - rule_id: "census_vs_estimated_population"
      description: "Estimated populations should align with census data"
      validation_type: "cross_reference"
      primary_dataset: "estimated_population"
      reference_dataset: "census_population"
      tolerance_percent: 10.0
      severity: "warning"
      
  health_vs_demographic:
    - rule_id: "health_rates_demographic_plausibility"
      description: "Health rates should be plausible given demographics"
      validation_type: "correlation_check"
      primary_columns: ["mortality_rate", "hospitalisation_rate"]
      reference_columns: ["median_age", "seifa_disadvantage_score"]
      expected_correlation_direction: "positive"
      min_correlation: 0.1
      severity: "info"

# Data freshness and versioning rules
data_governance:
  versioning:
    - rule_id: "data_version_format"
      description: "Data version should follow semantic versioning"
      validation_type: "pattern"
      column: "data_version"
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
      severity: "warning"
      
  freshness:
    - rule_id: "census_data_currency"
      description: "Census data should not be older than expected"
      validation_type: "temporal_freshness"
      column: "census_year"
      max_age_years: 5
      severity: "info"

# Reference data validation
reference_data:
  valid_postcodes:
    source: "australia_post_postcodes"
    refresh_frequency: "monthly"
    
  valid_sa2_codes:
    source: "abs_asgs_2021"
    refresh_frequency: "annually"
    
  icd_10_codes:
    source: "who_icd_10_am"
    refresh_frequency: "annually"

# Custom validation functions
custom_validators:
  indigenous_population_validator:
    description: "Validate indigenous population percentages"
    function: "validate_indigenous_population_percentage"
    parameters:
      max_percentage: 95.0
      
  remote_area_validator:
    description: "Apply different rules for remote areas"
    function: "apply_remote_area_rules"
    parameters:
      remote_area_threshold: 0.5  # Population per sq km