version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "team-leads"
    assignees:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "streamlit"
        update-types: ["version-update:semver-major"]
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
          - "bandit"
          - "coverage*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "pandas"
          - "streamlit*"
          - "polars*"
          - "geopandas"
          - "folium"
          - "plotly"
          - "duckdb"
        update-types:
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "docker"
      include: "scope"