# dvc.yaml
# Describes the high-level ETL pipeline for DVC
# For more detailed pipeline orchestration, refer to configs/pipelines/

vars:
  - configs/default.yaml

stages:
  extract_all_sources:
    cmd: python test_extraction.py
    deps:
      - src/extractors
      - configs/extractors
    params:
      - pipeline.enabled
    outs:
      - data_raw:
          cache: false

  integrate_master_data:
    cmd: ahgd-transform --input data_raw --output data_processed/master_health_record.parquet
    deps:
      - src/pipelines
      - src/transformers
      - data_raw
      - configs/pipelines
      - configs/integration
    params:
      - pipeline.enabled
    outs:
      - data_processed/master_health_record.parquet:
          cache: true
    metrics:
      - reports/quality_reports/integration_summary.json:
          cache: false

  validate_master_data:
    cmd: ahgd-validate --input data_processed/master_health_record.parquet --rules schemas/ --report reports/validation_report.html
    deps:
      - src/validators
      - data_processed/master_health_record.parquet
      - configs/validation
    outs:
      - reports/validation_report.html:
          cache: false

  export_final_data:
    cmd: ahgd-loader --input data_processed/master_health_record.parquet --output data_exports
    deps:
      - src/loaders
      - data_processed/master_health_record.parquet
      - configs/exports
    outs:
      - data_exports:
          cache: false