stages:
  download:
    cmd: python scripts/download_data.py
    deps:
      - scripts/download_data.py
      - configs/data_sources.yaml
    outs:
      - data_raw
    params:
      - download.sources
      - download.timeout
    metrics:
      - logs/download_metrics.json:
          cache: false

  preprocess:
    cmd: python scripts/preprocess_data.py
    deps:
      - scripts/preprocess_data.py
      - data_raw
    outs:
      - data_processed/cleaned
    params:
      - preprocess.remove_duplicates
      - preprocess.handle_missing
      - preprocess.date_format
    metrics:
      - logs/preprocess_metrics.json:
          cache: false

  extract_features:
    cmd: python scripts/extract_features.py
    deps:
      - scripts/extract_features.py
      - data_processed/cleaned
    outs:
      - data_processed/features
    params:
      - features.demographic
      - features.geographic
      - features.health_indicators
    metrics:
      - logs/feature_metrics.json:
          cache: false

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - scripts/train_model.py
      - data_processed/features
    outs:
      - models/health_predictor.pkl
    params:
      - model.type
      - model.hyperparameters
      - model.validation_split
    metrics:
      - logs/model_metrics.json:
          cache: false
    plots:
      - logs/confusion_matrix.csv:
          template: confusion
          x: actual
          y: predicted
      - logs/learning_curve.csv:
          template: linear
          x: epoch
          y: loss

  evaluate:
    cmd: python scripts/evaluate_model.py
    deps:
      - scripts/evaluate_model.py
      - models/health_predictor.pkl
      - data_processed/features
    metrics:
      - logs/evaluation_metrics.json:
          cache: false
    plots:
      - logs/roc_curve.csv:
          template: simple
          x: fpr
          y: tpr
      - logs/feature_importance.csv:
          template: bar_horizontal
          x: importance
          y: feature

  generate_report:
    cmd: python scripts/generate_report.py
    deps:
      - scripts/generate_report.py
      - logs/evaluation_metrics.json
      - models/health_predictor.pkl
    outs:
      - reports/health_analysis_report.html
      - reports/health_analysis_report.pdf