# Data Processing Parameters
data_processing:
  chunk_size: 10000
  memory_limit: "4GB"
  compression: "snappy"
  
# Geographic Parameters
geographic:
  crs: "EPSG:4326"  # WGS84
  simplify_tolerance: 0.001
  
# Analysis Parameters
analysis:
  correlation_threshold: 0.3
  significance_level: 0.05
  bootstrap_samples: 1000
  
# Health Indicators
health_indicators:
  - mortality_rate
  - life_expectancy
  - disease_prevalence
  - hospital_admissions
  
# Socioeconomic Indicators  
socioeconomic_indicators:
  - seifa_score
  - median_income
  - education_level
  - employment_rate
  
# Performance Settings
performance:
  parallel_processing: true
  max_workers: 4
  cache_size: "2GB"
  
# Output Settings
output:
  plot_dpi: 300
  figure_size: [12, 8]
  export_formats: ["png", "svg", "pdf"]