# Spatial Validation Configuration for AHGD Geographic Pipeline
#
# This file defines comprehensive validation rules and tolerances for
# geographic data processing, ensuring data quality and compliance with
# Australian Bureau of Statistics standards.

# Default validation settings
default_settings:
  enable_validation: true
  strict_mode: false
  fail_on_warnings: false
  generate_validation_report: true
  log_all_validations: false
  log_failures_only: true

# Coordinate System Validation
coordinate_system_validation:
  
  # Supported coordinate systems
  allowed_systems:
    - "GDA2020"
    - "GDA94"
    - "WGS84"
    - "AGD66"
    - "AGD84"
    
  # Target system requirements
  target_system: "GDA2020"
  enforce_target_system: true
  
  # Transformation validation
  transformation_validation:
    enable_round_trip_tests: true
    maximum_round_trip_error_metres: 1.0
    test_sample_size: 100
    
  # Precision requirements
  precision_requirements:
    minimum_decimal_places: 6
    maximum_decimal_places: 12
    enforce_precision: false  # Warning only
    
  # EPSG code validation
  epsg_validation:
    require_epsg_code: true
    validate_epsg_definition: true
    allowed_epsg_codes:
      - 7844  # GDA2020
      - 4283  # GDA94
      - 4326  # WGS84
      - 4202  # AGD66
      - 4203  # AGD84

# Geographic Bounds Validation
geographic_bounds:
  
  # Australian territory bounds
  australian_bounds:
    
    # Mainland Australia
    mainland:
      min_longitude: 112.5
      max_longitude: 154.0
      min_latitude: -39.5
      max_latitude: -10.0
      enforce: false  # Warning for mainland-only data
      
    # All territories (including external)
    all_territories:
      min_longitude: 96.0   # Cocos Islands
      max_longitude: 169.0  # Norfolk Island
      min_latitude: -55.0   # Macquarie Island
      max_latitude: -9.0    # Torres Strait
      enforce: true
      
    # Extended validation zone (allows for slight coordinate errors)
    validation_zone:
      min_longitude: 95.0
      max_longitude: 170.0
      min_latitude: -56.0
      max_latitude: -8.0
      
  # State-specific bounds validation
  state_bounds_validation:
    enable: true
    tolerance_degrees: 0.1  # Allow 0.1 degree tolerance for border areas
    
    state_bounds:
      NSW:
        min_longitude: 140.9
        max_longitude: 153.7
        min_latitude: -37.6
        max_latitude: -28.1
        
      VIC:
        min_longitude: 140.9
        max_longitude: 150.0
        min_latitude: -39.3
        max_latitude: -33.9
        
      QLD:
        min_longitude: 137.9
        max_longitude: 153.6
        min_latitude: -29.2
        max_latitude: -9.1
        
      SA:
        min_longitude: 129.0
        max_longitude: 141.1
        min_latitude: -38.1
        max_latitude: -25.9
        
      WA:
        min_longitude: 112.9
        max_longitude: 129.1
        min_latitude: -35.2
        max_latitude: -13.6
        
      TAS:
        min_longitude: 143.8
        max_longitude: 148.5
        min_latitude: -43.7
        max_latitude: -39.5
        
      NT:
        min_longitude: 129.0
        max_longitude: 138.1
        min_latitude: -26.1
        max_latitude: -10.9
        
      ACT:
        min_longitude: 148.7
        max_longitude: 149.5
        min_latitude: -36.0
        max_latitude: -35.1

# Geometry Validation
geometry_validation:
  
  # Basic geometry checks
  basic_checks:
    
    # Point validation
    point_validation:
      check_coordinate_validity: true
      check_australian_bounds: true
      allow_null_coordinates: false
      
    # Line validation
    line_validation:
      minimum_points: 2
      check_self_intersection: true
      check_duplicate_points: true
      
    # Polygon validation
    polygon_validation:
      minimum_points: 4
      check_ring_closure: true
      check_ring_orientation: true
      check_self_intersection: true
      check_interior_rings: true
      
  # Advanced geometry checks
  advanced_checks:
    
    # Topology validation
    topology_validation:
      check_validity: true
      check_simplicity: true
      repair_invalid_geometry: true
      
    # Area and perimeter validation
    area_validation:
      minimum_area_sqm: 1.0         # 1 square metre minimum
      maximum_area_sqkm: 2500000.0  # Australia's total area
      flag_suspicious_areas: true
      
    perimeter_validation:
      minimum_perimeter_m: 4.0      # 4 metres minimum (1m x 1m square)
      maximum_perimeter_km: 50000.0 # Australia's coastline length
      
  # Spatial relationship validation
  spatial_relationships:
    
    # Containment validation
    containment_checks:
      check_hierarchy_containment: true
      tolerance_metres: 10.0
      
    # Overlap validation
    overlap_checks:
      check_overlaps: true
      maximum_overlap_percent: 1.0  # 1% maximum overlap
      
    # Gap validation
    gap_checks:
      check_gaps: true
      maximum_gap_metres: 100.0
      
  # Coordinate validation
  coordinate_validation:
    
    # Precision validation
    precision_checks:
      check_coordinate_precision: true
      minimum_significant_digits: 6
      maximum_coordinate_digits: 15
      
    # Range validation
    range_checks:
      longitude_range: [-180.0, 180.0]
      latitude_range: [-90.0, 90.0]
      elevation_range: [-500.0, 5000.0]  # Metres above/below sea level

# Statistical Area Validation
statistical_area_validation:
  
  # Hierarchy validation
  hierarchy_validation:
    
    # Code format validation
    code_formats:
      SA1: "^\\d{11}$"    # 11 digits
      SA2: "^\\d{9}$"     # 9 digits
      SA3: "^\\d{5}$"     # 5 digits
      SA4: "^\\d{3}$"     # 3 digits
      STATE: "^\\d{1}$"   # 1 digit
      
    # Hierarchical containment
    containment_rules:
      enforce_strict_containment: true
      allow_boundary_touching: true
      containment_tolerance_metres: 1.0
      
    # Code relationship validation
    code_relationships:
      validate_parent_child_codes: true
      SA1_contains_SA2_prefix: true
      SA2_contains_SA3_prefix: true
      SA3_contains_SA4_prefix: true
      SA4_contains_STATE_prefix: true
      
  # Population constraints
  population_constraints:
    
    # SA1 constraints
    SA1_population:
      minimum: 200
      maximum: 800
      target: 400
      tolerance_percent: 20
      
    # SA2 constraints  
    SA2_population:
      minimum: 3000
      maximum: 25000
      target: 10000
      tolerance_percent: 50
      
    # SA3 constraints
    SA3_population:
      minimum: 30000
      maximum: 130000
      target: 80000
      tolerance_percent: 30
      
    # SA4 constraints
    SA4_population:
      minimum: 100000
      maximum: 500000
      target: 300000
      tolerance_percent: 40
      
  # Area constraints
  area_constraints:
    
    # Urban vs rural area rules
    urban_areas:
      maximum_area_sqkm: 100
      minimum_population_density: 1000  # people per sqkm
      
    rural_areas:
      maximum_area_sqkm: 50000
      minimum_population_density: 0.1   # people per sqkm
      
  # Naming validation
  naming_validation:
    
    # Name format rules
    name_format:
      maximum_length: 50
      allowed_characters: "^[A-Za-z0-9 \\-\\(\\)\\.,']+$"
      require_title_case: false
      no_leading_trailing_spaces: true
      
    # Name uniqueness
    uniqueness_rules:
      unique_within_parent: true
      unique_within_state: false
      case_sensitive: false

# Postcode Validation
postcode_validation:
  
  # Format validation
  format_validation:
    postcode_format: "^\\d{4}$"  # 4 digits
    leading_zeros_required: true
    
  # Range validation
  range_validation:
    
    # Valid Australian postcode ranges
    valid_ranges:
      NSW: [[1000, 1999], [2000, 2599], [2619, 2899], [2921, 2999]]
      ACT: [[200, 299], [2600, 2618], [2900, 2920]]
      VIC: [[3000, 3999], [8000, 8999]]
      QLD: [[4000, 4999], [9000, 9999]]
      SA: [[5000, 5999]]
      WA: [[6000, 6999]]
      TAS: [[7000, 7999]]
      NT: [[800, 999]]
      
    # Special postcodes
    special_postcodes:
      military: [2800, 2801, 2802]  # Military postcodes
      diplomatic: [200, 201, 202]   # Diplomatic postcodes
      
  # Geographic validation
  geographic_validation:
    validate_postcode_location: true
    tolerance_km: 50  # Postcode centroid within 50km of expected location
    
  # Correspondence validation
  correspondence_validation:
    require_sa2_mapping: true
    validate_allocation_factors: true
    maximum_sa2_per_postcode: 50

# Data Quality Thresholds
data_quality_thresholds:
  
  # Completeness thresholds
  completeness:
    minimum_record_completeness: 0.95    # 95% of records must be complete
    minimum_field_completeness: 0.90     # 90% of fields must be populated
    require_mandatory_fields: true
    
  # Accuracy thresholds
  accuracy:
    maximum_coordinate_error_metres: 10.0
    maximum_area_error_percent: 5.0
    maximum_perimeter_error_percent: 10.0
    
  # Consistency thresholds
  consistency:
    maximum_inconsistency_rate: 0.05     # 5% maximum inconsistency rate
    cross_validation_tolerance: 0.02     # 2% tolerance for cross-validation
    
  # Timeliness thresholds
  timeliness:
    maximum_data_age_days: 365           # Data older than 1 year flagged
    require_reference_date: true
    validate_temporal_consistency: true

# Validation Error Handling
error_handling:
  
  # Error classification
  error_severity:
    
    # Critical errors (fail validation)
    critical:
      - "invalid_coordinate_system"
      - "coordinates_outside_validation_zone"
      - "invalid_geometry_topology"
      - "missing_mandatory_fields"
      
    # Major errors (warnings, may fail in strict mode)
    major:
      - "coordinates_outside_australian_bounds"
      - "invalid_statistical_area_hierarchy"
      - "population_constraints_violated"
      - "invalid_postcode_format"
      
    # Minor errors (warnings only)
    minor:
      - "precision_below_recommended"
      - "naming_convention_violations"
      - "minor_topology_issues"
      - "data_quality_concerns"
      
  # Error reporting
  error_reporting:
    generate_error_summary: true
    include_error_details: true
    export_error_locations: true
    create_error_visualization: true
    
  # Error correction
  error_correction:
    enable_auto_correction: true
    
    # Auto-correctable errors
    auto_correctable:
      - "coordinate_precision_issues"
      - "minor_topology_errors"
      - "formatting_inconsistencies"
      
    # Manual review required
    manual_review_required:
      - "coordinate_system_conflicts"
      - "major_boundary_discrepancies"
      - "population_data_inconsistencies"

# Performance and Monitoring
performance_monitoring:
  
  # Processing performance
  processing_metrics:
    track_validation_time: true
    track_memory_usage: true
    track_throughput: true
    
  # Quality metrics
  quality_metrics:
    calculate_quality_scores: true
    track_error_rates: true
    monitor_data_drift: true
    
  # Benchmarking
  benchmarks:
    maximum_validation_time_seconds: 300   # 5 minutes maximum
    maximum_memory_usage_mb: 2048          # 2GB maximum
    minimum_throughput_records_per_second: 100
    
  # Alerting
  alerting:
    enable_performance_alerts: true
    enable_quality_alerts: true
    
    # Alert thresholds
    alert_thresholds:
      validation_time_seconds: 600         # 10 minutes
      error_rate_percent: 10.0            # 10% error rate
      quality_score_minimum: 0.8          # 80% quality score

# Integration and Output
integration:
  
  # Validation reporting
  reporting:
    
    # Report formats
    report_formats:
      - "json"
      - "html"
      - "csv"
      - "xml"
      
    # Report content
    include_summary_statistics: true
    include_detailed_errors: true
    include_recommendations: true
    include_visualizations: true
    
  # Database integration
  database_logging:
    log_validation_results: true
    store_error_details: true
    track_validation_history: true
    
  # External service integration
  external_validation:
    enable_third_party_validation: false
    validation_service_url: ""
    validation_service_timeout: 30
    
# Environment-specific Overrides
environment_overrides:
  
  # Development environment
  development:
    strict_mode: false
    fail_on_warnings: false
    enable_auto_correction: true
    log_all_validations: true
    
  # Testing environment
  testing:
    strict_mode: true
    fail_on_warnings: true
    enable_auto_correction: false
    comprehensive_validation: true
    
  # Production environment
  production:
    strict_mode: true
    fail_on_warnings: false
    enable_auto_correction: true
    performance_optimised: true