# Column Mappings Configuration
# Maps source data columns to target schema columns

# Geographic mappings
geographic:
  sa1:
    source_columns:
      code: ["SA1_CODE_2021", "SA1_CODE_2"]  # Full and truncated versions
      name: ["SA1_NAME_2021", "SA1_NAME_2"]
      state_code: ["STE_CODE_2021", "STE_CODE_2"]
      state_name: ["STE_NAME_2021", "STE_NAME_2"]
    level: "SA1"
  sa2:
    source_columns:
      code: ["SA2_CODE_2021", "SA2_CODE_2"]
      name: ["SA2_NAME_2021", "SA2_NAME_2"]
      state_code: ["STE_CODE_2021", "STE_CODE_2"]
      state_name: ["STE_NAME_2021", "STE_NAME_2"]
    level: "SA2"
  sa3:
    source_columns:
      code: ["SA3_CODE_2021", "SA3_CODE_2"]
      name: ["SA3_NAME_2021", "SA3_NAME_2"]
      state_code: ["STE_CODE_2021", "STE_CODE_2"]
      state_name: ["STE_NAME_2021", "STE_NAME_2"]
    level: "SA3"
  sa4:
    source_columns:
      code: ["SA4_CODE_2021", "SA4_CODE_2"]
      name: ["SA4_NAME_2021", "SA4_NAME_2"]
      state_code: ["STE_CODE_2021", "STE_CODE_2"]
      state_name: ["STE_NAME_2021", "STE_NAME_2"]
    level: "SA4"
  ste:
    source_columns:
      code: ["STE_CODE_2021", "STE_CODE_2"]
      name: ["STE_NAME_2021", "STE_NAME_2"]
    level: "STE"
  poa:
    source_columns:
      code: ["POA_CODE_2021", "POA_CODE_2"]
      name: ["POA_NAME_2021", "POA_NAME_2"]
    level: "POA"

# Census table mappings
census:
  # G01 - Selected Person Characteristics by Sex
  G01:
    file_pattern: "2021Census_G01_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    measures:
      - source: "Tot_P_P"
        target: "total_persons"
        description: "Total Persons"
      - source: "Tot_P_M"
        target: "male_persons"
        description: "Total Males"
      - source: "Tot_P_F"
        target: "female_persons"
        description: "Total Females"

  # G17 - Total Personal Income (Weekly) by Age by Sex
  G17:
    file_pattern: "2021Census_G17[A-C]_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    unpivot_patterns:
      income_brackets:
        pattern: "P_(.+)_Tot"
        value_mapping:
          "Neg_Nil_income": "Negative/Nil income"
          "1_149": "$1-$149"
          "150_299": "$150-$299"
          "300_399": "$300-$399"
          "400_499": "$400-$499"
          "500_649": "$500-$649"
          "650_799": "$650-$799"
          "800_999": "$800-$999"
          "1000_1249": "$1000-$1249"
          "1250_1499": "$1250-$1499"
          "1500_1749": "$1500-$1749"
          "1750_1999": "$1750-$1999"
          "2000_2999": "$2000-$2999"
          "3000_more": "$3000 or more"
          "NS": "Not stated"

  # G18 - Core Activity Need for Assistance by Age by Sex
  G18:
    file_pattern: "2021Census_G18_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    measures:
      assistance_status:
        has_need: "P_Tot_Need_for_assistance"
        no_need: "P_Tot_No_need_for_assistance"
        not_stated: "P_Tot_Need_not_stated"

  # G19 - Type of Long-Term Health Condition by Sex
  G19:
    file_pattern: "2021Census_G19_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    conditions:
      - code: "ARTHRITIS"
        source_column: "P_Arthritis_Tot"
        name: "Arthritis"
        category: "Musculoskeletal"
      - code: "ASTHMA"
        source_column: "P_Asthma_Tot"
        name: "Asthma"
        category: "Respiratory"
      - code: "CANCER"
        source_column: "P_Cancer_Tot"
        name: "Cancer (including remission)"
        category: "Cancer"
      - code: "DEMENTIA"
        source_column: "P_Dementia_Tot"
        name: "Dementia (including Alzheimer's)"
        category: "Neurological"
      - code: "DIABETES"
        source_column: "P_Diabetes_Tot"
        name: "Diabetes (excluding gestational)"
        category: "Metabolic"
      - code: "HEART_DISEASE"
        source_column: "P_Heart_disease_Tot"
        name: "Heart disease (including heart attack or angina)"
        category: "Cardiovascular"
      - code: "KIDNEY_DISEASE"
        source_column: "P_Kidney_disease_Tot"
        name: "Kidney disease"
        category: "Renal"
      - code: "LUNG_CONDITION"
        source_column: "P_Lung_condition_Tot"
        name: "Lung condition (including COPD or emphysema)"
        category: "Respiratory"
      - code: "MENTAL_HEALTH"
        source_column: "P_Mental_health_condition_Tot"
        name: "Mental health condition (including depression or anxiety)"
        category: "Mental Health"
      - code: "STROKE"
        source_column: "P_Stroke_Tot"
        name: "Stroke"
        category: "Cardiovascular"
      - code: "OTHER"
        source_column: "P_Other_Tot"
        name: "Other long-term health condition(s)"
        category: "Other"

  # G20 - Count of Selected Long-Term Health Conditions by Sex
  G20:
    file_pattern: "2021Census_G20_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    condition_counts:
      - source: "P_0_Cond_Tot"
        value: "0 conditions"
      - source: "P_1_Cond_Tot"
        value: "1 condition"
      - source: "P_2_Cond_Tot"
        value: "2 conditions"
      - source: "P_3_Cond_Tot"
        value: "3 conditions"
      - source: "P_4_Cond_Tot"
        value: "4 conditions"
      - source: "P_5_Cond_Tot"
        value: "5 conditions"
      - source: "P_6_more_Cond_Tot"
        value: "6 or more conditions"

  # G21 - Selected Long-Term Health Conditions by Selected Characteristics
  G21:
    file_pattern: "2021Census_G21_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    characteristics:
      country_of_birth:
        - code: "BORN_AUSTRALIA"
          value: "Australia"
          columns_suffix: "_COB_Australia"
      labour_force:
        - code: "EMPLOYED"
          value: "Employed"
          columns_suffix: "_LF_Employed"
        - code: "UNEMPLOYED"
          value: "Unemployed"
          columns_suffix: "_LF_Unemployed"
        - code: "NOT_IN_LF"
          value: "Not in labour force"
          columns_suffix: "_LF_Not_in_LF"

  # G25 - Unpaid Assistance to a Person with a Disability by Age by Sex
  G25:
    file_pattern: "2021Census_G25_AUS_SA\\d+\\.csv"
    header_rows: 1
    index_column: "SA1_CODE_2021"
    assistance_provision:
      provided: "P_Tot_prvided_unpaid_assist"
      not_provided: "P_Tot_no_unpaid_assist"
      not_stated: "P_Tot_unpaid_assist_ns"

# Standard demographic mappings
demographics:
  age_groups:
    - "0-4"
    - "5-9"
    - "10-14"
    - "15-19"
    - "20-24"
    - "25-29"
    - "30-34"
    - "35-39"
    - "40-44"
    - "45-49"
    - "50-54"
    - "55-59"
    - "60-64"
    - "65-69"
    - "70-74"
    - "75-79"
    - "80-84"
    - "85+"
  sex_categories:
    - "Male"
    - "Female"
    - "Persons"

# Person characteristics types
characteristic_types:
  income_bracket:
    category: "Economic"
    values:
      - "Negative/Nil income"
      - "$1-$149"
      - "$150-$299"
      - "$300-$399"
      - "$400-$499"
      - "$500-$649"
      - "$650-$799"
      - "$800-$999"
      - "$1000-$1249"
      - "$1250-$1499"
      - "$1500-$1749"
      - "$1750-$1999"
      - "$2000-$2999"
      - "$3000 or more"
      - "Not stated"
  
  assistance_need_status:
    category: "Health"
    values:
      - "Needs Assistance"
      - "No Need"
      - "Not Stated"
  
  assistance_provision_status:
    category: "Social"
    values:
      - "Provided"
      - "Not Provided"
      - "Not Stated"
  
  condition_count:
    category: "Health"
    values:
      - "0 conditions"
      - "1 condition"
      - "2 conditions"
      - "3 conditions"
      - "4 conditions"
      - "5 conditions"
      - "6 or more conditions"
  
  country_of_birth:
    category: "Social"
    values:
      - "Australia"
      - "Other"
      - "Not Stated"
  
  labour_force_status:
    category: "Economic"
    values:
      - "Employed"
      - "Unemployed"
      - "Not in labour force"
      - "Not Stated"