# Data Sources Configuration
# URLs for ABS Geographic and Census data

geographic:
  # Note: These are placeholder URLs as the actual ABS URLs require authentication
  # In production, you would need to:
  # 1. Register with ABS for data access
  # 2. Use authenticated download methods
  # 3. Or manually download files and place in data/raw/geographic/
  base_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
  asgs_2021:
    sa1:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_sa1_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
    sa2:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_sa2_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
    sa3:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_sa3_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
    sa4:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_sa4_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
    ste:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_ste_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"
    poa:
      url: "MANUAL_DOWNLOAD_REQUIRED"
      filename: "1270055001_poa_2021_aust_shape.zip"
      manual_url: "https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/access-and-downloads/digital-boundary-files"

census:
  base_url: "https://www.abs.gov.au/census/find-census-data/datapacks"
  gcp_2021:
    all_australia:
      url: "https://www.abs.gov.au/census/find-census-data/datapacks/download/2021_GCP_all_for_AUS_short-header.zip"
      filename: "2021_GCP_all_for_AUS_short-header.zip"
      tables:
        - G01  # Selected Person Characteristics by Sex
        - G17  # Total Personal Income (Weekly) by Age by Sex
        - G18  # Core Activity Need for Assistance by Age by Sex
        - G19  # Type of Long-Term Health Condition by Sex
        - G20  # Count of Selected Long-Term Health Conditions by Sex
        - G21  # Selected Long-Term Health Conditions by Selected Characteristics
        - G25  # Unpaid Assistance to a Person with a Disability by Age by Sex

  # Census date configuration
  date: "2021-08-10"
  year: 2021